<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.simplejavamail</groupId>
		<artifactId>smtp-connection-pool-parent</artifactId>
		<version>4.0.0</version>
	</parent>

	<artifactId>smtp-connection-pool-jakarta-provider</artifactId>
	<packaging>jar</packaging>
	<name>SMTP Connection Pool :: Jakarta Mail Provider</name>
	<description>Jakarta Mail smtppool Transport provider backed by smtp-connection-pool.</description>

	<properties>
		<automaticModuleName>org.simplejavamail.smtpconnectionpool.jakarta</automaticModuleName>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.simplejavamail</groupId>
			<artifactId>smtp-connection-pool</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.mail</groupId>
			<artifactId>jakarta.mail-api</artifactId>
		</dependency>

		<dependency>
			<groupId>org.eclipse.angus</groupId>
			<artifactId>angus-mail</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
